### ISSUE TITLE
Cannot invoke "ghidra.program.model.mem.MemoryBlock.getData()" because "rodata" is null

### ISSUE THREAD

**Issue by uniformization** [DMaroo/GhidRust#3]
Whenever I try to load any rust application built for windows (x86, LE) onto the CodeBrowser on Windows, I'll get a plugin event error with the following stack traces:

```
Cannot invoke "ghidra.program.model.mem.MemoryBlock.getData()" because "rodata" is null
java.lang.NullPointerException: Cannot invoke "ghidra.program.model.mem.MemoryBlock.getData()" because "rodata" is null
	at ghidrust.analyzer.RustStdAnalyzer.isRustBinary(RustStdAnalyzer.java:177)
	at ghidrust.analyzer.RustStdAnalyzer.canAnalyze(RustStdAnalyzer.java:127)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.initializeAnalyzers(AutoAnalysisManager.java:165)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.<init>(AutoAnalysisManager.java:147)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.getAnalysisManager(AutoAnalysisManager.java:983)
	at ghidra.app.plugin.core.analysis.AutoAnalysisPlugin.programOpened(AutoAnalysisPlugin.java:249)
	at ghidra.app.plugin.core.analysis.AutoAnalysisPlugin.processEvent(AutoAnalysisPlugin.java:233)
	at ghidra.framework.plugintool.Plugin.eventSent(Plugin.java:292)
	at ghidra.framework.plugintool.mgr.EventManager.sendEvents(EventManager.java:286)
	at ghidra.framework.plugintool.mgr.EventManager.lambda$new$3(EventManager.java:49)
	at ghidra.util.Swing.doRun(Swing.java:292)
	at ghidra.util.Swing.runNow(Swing.java:208)
	at ghidra.util.Swing.runNow(Swing.java:163)
	at ghidra.framework.plugintool.mgr.EventManager.fireEvent(EventManager.java:216)
	at ghidra.framework.plugintool.PluginTool.firePluginEvent(PluginTool.java:502)
	at ghidra.framework.plugintool.Plugin.firePluginEvent(Plugin.java:444)
	at ghidra.app.plugin.core.progmgr.MultiProgramManager.fireOpenEvents(MultiProgramManager.java:267)
	at ghidra.app.plugin.core.progmgr.MultiProgramManager.addProgram(MultiProgramManager.java:95)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.lambda$openProgram$6(ProgramManagerPlugin.java:469)
	at ghidra.util.Swing.doRun(Swing.java:292)
	at ghidra.util.Swing.runNow(Swing.java:208)
	at ghidra.util.Swing.runNow(Swing.java:163)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.openProgram(ProgramManagerPlugin.java:475)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.openPrograms(ProgramManagerPlugin.java:658)
	at ghidra.app.plugin.core.progmgr.ProgramManagerPlugin.acceptData(ProgramManagerPlugin.java:129)
	at ghidra.framework.plugintool.PluginManager.acceptData(PluginManager.java:48)
	at ghidra.framework.plugintool.PluginTool.acceptDomainFiles(PluginTool.java:441)
	at ghidra.framework.main.ToolButton.openDomainFiles(ToolButton.java:631)
	at ghidra.framework.main.ToolButton$2.end(ToolButton.java:609)
	at ghidra.framework.main.ZoomImageRunner$1.end(ZoomImageRunner.java:54)
	at org.jdesktop.animation.timing.Animator.end(Animator.java:755)
	at org.jdesktop.animation.timing.Animator.stop(Animator.java:660)
	at org.jdesktop.animation.timing.Animator.timingEvent(Animator.java:732)
	at org.jdesktop.animation.timing.Animator.access$200(Animator.java:75)
	at org.jdesktop.animation.timing.Animator$TimerTarget.actionPerformed(Animator.java:1041)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

```
Cannot invoke "ghidra.program.model.mem.MemoryBlock.getData()" because "rodata" is null
java.lang.NullPointerException: Cannot invoke "ghidra.program.model.mem.MemoryBlock.getData()" because "rodata" is null
	at ghidrust.analyzer.RustStdAnalyzer.isRustBinary(RustStdAnalyzer.java:177)
	at ghidrust.analyzer.RustStdAnalyzer.canAnalyze(RustStdAnalyzer.java:127)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.initializeAnalyzers(AutoAnalysisManager.java:165)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.<init>(AutoAnalysisManager.java:147)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.getAnalysisManager(AutoAnalysisManager.java:983)
	at ghidra.app.plugin.core.analysis.AutoAnalysisPlugin.lambda$programActivated$4(AutoAnalysisPlugin.java:278)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

I'm on the lastest commit (08f9e914d2a4b8605bd406b911d376abbc08dfd6) of GhidRust on the latest Ghidra release (10.2.3)

**Comment by DMaroo** [comment]
I have removed looking for `.rodata` section, and now I just search through the program memory. This is completely portable. I request you test your binary again with the latest commit: b66c9091cc35e4b6c263e8985639d93c6c35cd10

**Comment by uniformization** [comment]
Thank you, the issue was resolved, however, I have another issue when running Auto Analysis when trying to detect Rust libstd functions:

```
Cannot invoke "java.io.BufferedWriter.close()" because "ghidrust.analyzer.RustStdAnalyzer.writer" is null
java.lang.NullPointerException: Cannot invoke "java.io.BufferedWriter.close()" because "ghidrust.analyzer.RustStdAnalyzer.writer" is null
	at ghidrust.analyzer.RustStdAnalyzer.analysisEnded(RustStdAnalyzer.java:117)
	at ghidra.app.plugin.core.analysis.AnalysisTaskList.notifyAnalysisEnded(AnalysisTaskList.java:142)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.notifyAnalysisEnded(AutoAnalysisManager.java:851)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:802)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:667)
	at ghidra.app.plugin.core.analysis.AutoAnalysisManager.startAnalysis(AutoAnalysisManager.java:632)
	at ghidra.app.plugin.core.analysis.AnalysisBackgroundCommand.applyTo(AnalysisBackgroundCommand.java:58)
	at ghidra.framework.plugintool.mgr.BackgroundCommandTask.run(BackgroundCommandTask.java:102)
	at ghidra.framework.plugintool.mgr.ToolTaskManager.run(ToolTaskManager.java:336)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by DMaroo** [comment]
Thank you. That's a nice catch. The local logging for any sort of debugging was still present in the code. I removed it. It should work now. Check the latest commit: 9550dd2717f8ca0c2bd55fe37b70082c9d316abd.

**Comment by uniformization** [comment]
GhidRust works now! Thank you!
